### ISSUE TITLE
Orca.pet/notonmyshift is down?  Alt address for lists?

### ISSUE THREAD

**Issue by TPS** [socram8888/not-on-my-shift#13]
@socram8888 httpS://orca.pet/notonmyshift is down, which is preventing access to your lists.  (Weirdly, [*blog*.orca.pet](httpS://blog.orca.pet) is just fine.) Could you fix &/or provide alternate subscription addresses (e.g., here on GitHub), as many do for such eventualities?

**Comment by socram8888** [comment]
Hello! blog.orca.pet is served by GitHub Pages, instead of Oracle Cloud. Ubuntu Server did an oopsie yesterday while upgrading to 22.04, and disabled for some mysterious reasons all the services running on the machine.

Regarding hosting it on GitHub, I'd rather not - eventually I wanna move it into a proper webapp for managing the domains instead of a YAML-based approach, and that'd prevent me from setting up a 307 once that happens.

**Comment by TPS** [comment]
Everything's back.  Thanks! 🙇🏾‍♂️

What do you think of also posting the lists here?
